name: H4B Website
on:
  pull_request:
    branches: [main, production]
  workflow_dispatch:

jobs:
  format:
    name: formatting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: acm-ucr/formatting@v2

  lint:
    name: linting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: acm-ucr/linting@v2

  images:
    name: images
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: acm-ucr/images@v2
        with:
          branch: ${{ github.head_ref }}
